inference:
  device: "cuda"  # или "cpu"
  target_size: [256, 256]  # (height, width)
  threshold: 0.5
  batch_size: 16

paths:
  weights_dir: "weights"
  default_model: "unet_resnet34"

preprocessing: # параметры распределений, соотвествующие распределению цветов в ImageNet (энкодеры были предобучены на нем)
  mean: [0.485, 0.456, 0.406] 
  std: [0.229, 0.224, 0.225]